In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r'mpg.csv')
df.head()

In [ ]:
labels = df.columns.to_list()
labels

In [ ]:
df.describe()

In [ ]:
df[df['horsepower'].isna()]['horsepower']

In [ ]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())
df[df['horsepower'].isna()]['horsepower']

In [ ]:
df.info()

In [ ]:
df.isna().sum()

In [ ]:
labels

In [ ]:
df.info()

In [ ]:
y_label = labels.pop(0)
X_labels = labels
X_labels.remove('car_name')
X_labels , y_label

In [ ]:
from sklearn.model_selection import train_test_split
X = df[X_labels]
y = df[y_label]
# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn import linear_model
reg = linear_model.LinearRegression()

reg.fit(X_train, y_train)
reg.coef_, reg.intercept_

In [ ]:
y_predict = reg.predict(X_test)
print(y_predict)
print(y_test.tolist())

In [ ]:
from sklearn.metrics import r2_score

r2_score(y_test, y_predict)

### polynomial Regression

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r'car_prices.csv')
df.head()

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df[['mileage']], df['selling_price'], test_size=0.2, random_state=21)
model = LinearRegression()
model.fit(X_train, y_train)

In [ ]:
model.intercept_

In [ ]:
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
plt.figure(figsize=(8,6))
plt.scatter(df['mileage'], df['selling_price'], marker='*')
plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['mileage']], df['selling_price'], test_size=0.2, random_state=21)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(2)
X_train_poly = poly.fit_transform(X_train)

In [ ]:
from sklearn.linear_model import LinearRegression
model_poly = LinearRegression()
model_poly.fit(X_train_poly, y_train)

In [ ]:
x_test_poly = poly.transform(X_test)
y_pred = model_poly.predict(x_test_poly)

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error


r2_score(y_test, y_pred), mean_squared_error(y_test, y_pred)

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
X_train.shape

In [ ]:
x_range = np.linspace(X_train['mileage'].min(), X_train['mileage'].max(), 240).reshape(-1,1)
x_range_poly = poly.transform(x_range)
y_range_pred = model_poly.predict(x_range_poly)

In [ ]:
plt.figure(figsize=(8,6))
plt.scatter(X_train['mileage'], y_train, label = 'Actual Data')
plt.plot(x_range, y_range_pred, color='orange', label='Polynomial Regression Line')
plt.title('Used Car Pricing: Polynomial Regression Fit')
plt.xlabel('Mileage')
plt.ylabel('Selling Price')
plt.legend()
plt.show()

### Encoding

In [ ]:
import pandas as pd

###

In [ ]:
df = pd.read_csv(r'mpg.csv')
df.head()

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
enc.fit(df[['car_name']])

In [ ]:
df['ordinal_car_name'] = enc.transform(df[['car_name']])
df.head()

Now your model might think:

Ford (2) > BMW (1) > Maruti (0)

as if there is some order or distance between them!

But that’s wrong ❌ — these are just names, not ordered values.
(“BMW” isn’t twice “Maruti”)

So — we need a way to represent categories without implying order.

In [ ]:
df = pd.DataFrame({
    'name': ['Aman', 'Riya', 'John'],
    'sales': [200, 150, 300],
    'city': ['Delhi', 'Mumbai', 'Goa']
})
df_drop_row = df.drop(1, axis=0)
print(df_drop_row)
df_drop_col = df.drop('city', axis=1)
print(df_drop_col)

### practical self implementation

In [ ]:
import pandas as pd
df = pd.read_csv(r'home_prices.csv')
df.head()

In [ ]:
df['locality'].unique()

In [ ]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()
encoded = enc.fit_transform(df[['locality']]).toarray()
# print(encoded)
columns = enc.get_feature_names_out(['locality'])
columns

In [ ]:
encoded_df = pd.DataFrame(encoded, columns=columns)
encoded_df.drop('locality_Mankhal', axis = 1, inplace=True)
# encoded_df = encoded_df.drop('locality_Kollur', axis = 1)
encoded_df.columns = encoded_df.columns.str.replace(" ", "_").str.lower()
encoded_df.head()

In [ ]:
df_merged = pd.concat([df.drop('locality', axis=1),encoded_df ], axis=1)
df_merged.head()

### One Hot Encoder

In [ ]:


df = pd.DataFrame({
    'Salary' : [10, 20, 30, 40, 50,],
    'age' : [1, 2, 3 , 4, 5],
    'name': ['A', 'B', 'C', 'D', 'E'],
    'gender' : ['male', 'female', 'male', 'female', 'male'],
    'location': ['kanpur', 'lucknow', 'kanpur', 'lucknow', 'kanpur'],
    'degree' : ['bsc', 'msc', 'phd', 'bsc', 'msc'],
    'level' : ['five', 'four', 'three', 'two', 'one']
})
df.head()

In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
# encoded =enc.fit_transform(X = df[['gender']]).toarray()
encoded =enc.fit_transform(X = df[['gender', 'location']]).toarray()
columns = enc.get_feature_names_out()
print(columns)
encoded_df = pd.DataFrame(encoded, columns=columns)
print(encoded_df)
print(enc.categories_)

combined_df = pd.concat([df.drop('gender', axis=1), encoded_df],axis=1) # later drop one column
print(combined_df)
print(df)

### Ordinal Encoder

In [ ]:
df = pd.DataFrame({
    'Salary' : [10, 20, 30, 40, 50,],
    'age' : [1, 2, 3 , 4, 5],
    'name': ['A', 'B', 'C', 'D', 'E'],
    'gender' : ['male', 'female', 'male', 'female', 'male'],
    'location': ['kanpur', 'lucknow', 'kanpur', 'lucknow', 'kanpur'],
    'degree' : ['bsc', 'msc', 'phd', 'bsc', 'msc'],
    'level' : ['five', 'four', 'three', 'two', 'one']
})
df.head()

In [ ]:
replace = {'bsc' : 0, 'msc' : 1, 'phd' : 2}
df['degree_ord'] = df['degree'].map(replace)
df.head()

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

categories = [['bsc', 'msc', 'phd'],
              ['one', 'two', 'three', 'four', 'five']]
enc = OrdinalEncoder(categories=categories)

columns = ['degree', 'level']
encoded = enc.fit_transform(df[columns])
columns_renamed = [col_name + '_ord' for col_name in columns]
encoded_df = pd.DataFrame(encoded, columns=columns_renamed)
encoded_df
combined_df = pd.concat([df, encoded_df], axis=1)
combined_df

### label Encoder

In [ ]:
df = pd.DataFrame({
    'Salary' : [10, 20, 30, 40, 50,],
    'age' : [1, 2, 3 , 4, 5],
    'name': ['A', 'B', 'C', 'D', 'E'],
    'gender' : ['male', 'female', 'male', 'female', 'male'],
    'location': ['kanpur', 'lucknow', 'kanpur', 'lucknow', 'kanpur'],
    'degree' : ['bsc', 'msc', 'phd', 'bsc', 'msc'],
    'level' : ['five', 'four', 'three', 'two', 'one'],
    'category' : ['spam','ham','spam','ham','spam']
})
df.head()

In [ ]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
encoded = enc.fit_transform(df['category']) #1dim array only
df['enc_category'] = pd.Series(encoded) # or just encoded
df.head()

### Scaling

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r'home_prices.csv')
df.head()

  locality  area_sqr_ft  price_lakhs  bedrooms
0   Kollur          656         39.0         2
1   Kollur         1260         83.2         2
2   Kollur         1057         86.6         3
3   Kollur         1259         59.0         2
4   Kollur         1800        140.0         3

In [26]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['area_sqr_ft','bedrooms']], df['price_lakhs'], test_size=0.4, random_state=21)
scaler_x = MinMaxScaler().fit(X_train)
scaler_y = MinMaxScaler().fit(y_train.values.reshape(-1,1)) #reshape needed  becuase it takes 2D

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
model = LinearRegression()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

r2_score(y_test, y_pred), mean_squared_error(y_test, y_pred) #(0.844511595397575, 1077.2871677821959)

(0.844511595397575, 1077.2871677821956)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
model = LinearRegression()
X_train_scaled = scaler_x.transform(X_train)
y_train_scaled = scaler_y.transform(y_train.values.reshape(-1,1))
model.fit(X_train_scaled,y_train_scaled)

X_test_scaled = scaler_x.transform(X_test)
y_pred_scaled = model.predict(X_test_scaled)
y_pred = scaler_y.inverse_transform(y_pred_scaled)

r2_score(y_test, y_pred), mean_squared_error(y_test, y_pred) #(0.844511595397575, 1077.2871677821959)

(0.844511595397575, 1077.2871677821959)

In [48]:

Q3 = df['price_lakhs'].quantile([0.75, 0.25])
Q3

0.75    147.5
0.25     67.5
Name: price_lakhs, dtype: float64

In [38]:
df.describe()

       area_sqr_ft  price_lakhs   bedrooms
count    22.000000    22.000000  22.000000
mean   1472.454545   129.313636   2.500000
std     518.796109    98.240338   0.511766
min     656.000000    39.000000   2.000000
25%    1102.500000    67.500000   2.000000
50%    1263.000000    85.800000   2.500000
75%    1687.500000   147.500000   3.000000
max    2600.000000   400.000000   3.000000